# Generated by Django 4.0.5 on 2022-07-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_arena_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='arena_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
