# Generated by Django 4.0.5 on 2022-07-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_arena_arena_number_round_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='arena_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(null=True),
        ),
    ]
