# Generated by Django 4.0.5 on 2022-07-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_result_result_alter_arena_arena_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='Gracze', to='app.player'),
        ),
    ]
