# Generated by Django 4.0.5 on 2022-07-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_acc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acc',
        ),
    ]
